### ISSUE TITLE
Release for 3.4 heap_size_envvars?

### ISSUE THREAD

**Issue by GloriousEggroll** [Firerat/wine-pba#1]
Hey man, thanks again for this, I just wanted to know if you could make a release for 3.4 heap_size_envvars branch. I'm incorporating the patches into my league of legends flatpak and would prefer to not have to pull from master. 

Also I found out guild wars 2 dx9 needs the heap size envvars as well, so ffxiv is not the only one

**Comment by Firerat** [comment]
I will maintain https://github.com/Firerat/wine-pba/tree/heap_size_envvars
that is actually based on the master https://github.com/acomminos/wine-pba patchset I unfuzzed for 3.4
it also seems to benefit witcher3 dx11 ( higher heap sizes fixes vegetation  )
It is probably worth me opening an issue upstream, so we can explore better default for PBA
and get my code reviewed, my c is extremely limited

pull from master?
`git clone git@github.com:Firerat/wine-pba.git -b heap_size_envvars --single-branch heap_size_envvars`
that will checkout just the heap_size_envvars branch into dir heap_size_envvars ( I have little imagination lol )

**Comment by GloriousEggroll** [comment]
the issue is in flatpak I am pulling master.zip using curl, as flatpak i dont believe has git support (i could be wrong):

# league of legends
curl -L -O http://archive.ubuntu.com/ubuntu/pool/main/o/openldap/openldap_2.4.42+dfsg.orig.tar.gz
curl -L https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks -o $NAME/files/bin/winetricks
curl -L -O https://github.com/wine-mirror/wine/archive/wine-3.4.tar.gz
curl -L -O https://github.com/wine-staging/wine-staging/archive/v3.4.tar.gz
curl -L -O https://github.com/sarnex/wine-d3d9-patches/archive/wine-d3d9-3.4.tar.gz

**Comment by Firerat** [comment]
ahh, yeah
I did push a tag, just before my laptop went to suspend ( no power )
https://github.com/Firerat/wine-pba/releases
that should have what you need

**Comment by GloriousEggroll** [comment]
perfect! thanks!
